### ISSUE TITLE
ctr-httpwn Problem.

### ISSUE THREAD

**Issue by Scarfman** [yellows8/ctr-httpwn#37]
Current version is 9.4.0-33U and I'm getting this error code.

![1f6240a2cece88d6b93f61bcd09edd8e6b9997f1f141174846 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/23647669/20509508/2a482eda-b037-11e6-8c26-10f116dadc8f.jpg)

**Comment by 141andTwoThirds** [comment]
That screenshot is impossibly small to read, but I'm going to assume that you're getting this message:

`httpcGetResponseStatusCode returned 0xd8a0a049. Config downloading failed: 0xd8a0a049. An error occured. If this is an actual issue not relating to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with a screenshot: https://github.com/yellows8/ctr-httpwn/issues`

If that's the case, that's because the files needed are currently unavailable. See this thread for more details: https://github.com/yellows8/browserhax_site/issues/17
